In [1]:
import numpy as np
np.random.seed(42)

In [19]:
a= np.random.multivariate_normal(mean=[0,0], cov= [[1.0, 0.5],[0.5,1.0]], size=100)
b= np.random.multivariate_normal(mean=[2.5,0], cov= [[1.2, -0.3],[-0.3,0.8]], size=100)

X= np.vstack((a,b))
y= np.array([0]*100 + [1]*100)
X.shape, y.shape, np.unique(y, return_counts=True)

((200, 2), (200,), (array([0, 1]), array([100, 100])))

In [ ]:
mu=X.mean(axis=0)
sigma=X.std(axis=0)
Z = (X - mu) / sigma
Z.mean(axis=0), Z.std(axis=0)

(array([ 2.40918396e-16, -2.15105711e-18]), array([1., 1.]))

In [35]:
w=np.array([0.9,-0.7])
b=0.1
s=Z.dot(w)+b
pred= (s>=0).astype(int)
accuracy= (pred==y).mean()
accuracy
tn= ((pred==0) & (y==0)).sum()
fn= ((pred==0) & (y==1)).sum()
tp= ((pred==1) & (y==1)).sum()
fp= ((pred==1) & (y==0)).sum()
confusion_matrix= np.array([[tn, fp],[fn, tp]])
confusion_matrix

array([[79, 21],
       [27, 73]])

In [ ]:
perm = np.random.permutation(len(Z))
Z = Z[perm]
y = y[perm]

n_train = int(0.7 * len(Z))
Z_train, Z_test = Z[:n_train], Z[n_train:]
y_train, y_test = y[:n_train], y[n_train:]

t_train = y_train * 2 - 1
t_test = y_test * 2 - 1


(array([-1,  1]), array([70, 70]))

In [43]:
phi_train = np.c_[np.ones(len(Z_train)), Z_train]
phi_test = np.c_[np.ones(len(Z_test)), Z_test]

w_hat = np.linalg.pinv(phi_train).dot(t_train)
print("Learned weights (bias, w1, w2)",w_hat)

Learned weights (bias, w1, w2) [ 0.00826603  0.71267738 -0.05919522]


In [47]:
score_test = phi_test.dot(w_hat)
pred_test = (score_test >= 0).astype(int)

accuracy_test = (pred_test == y_test).mean()
print("Test set accuracy:", round(accuracy_test,3))


Test set accuracy: 0.867


In [51]:
C = np.cov (Z, rowvar=False)
print("Covariance matrix:\n", C)

Covariance matrix:
 [[1.00502513 0.05466056]
 [0.05466056 1.00502513]]


In [ ]:
vals, vecs = np.linalg.eig(C)